0,NameError,name 'floor' is not defined,0,,2023-07-25 22:23:01.161986
1,ValueError,"The column ""state"" is not in the table. The table contains these columns: FMID, MarketName, street, city, County, State, zip, x, y, Website, Facebook, Twitter, Youtube, OtherMedia, Organic, Tofu, Bakedgoods, Cheese, Crafts, Flowers, Eggs, Seafood, Herbs, Vegetables, Honey, Jams, Maple, Meat, Nursery, Nuts, Plants, Poultry, Prepared, Soap, Trees, Wine, Coffee, Beans, Fruits, Grains, Juices, Mushrooms, PetFood, WildHarvested, updateTime, Location, Credit, WIC, WICcash, SFMNP, SNAP, Season1Date, Season1Time, Season2Date, Season2Time, Season3Date, Season3Time, Season4Date, Season4Time",0,,2023-07-25 22:59:03.599282
2,NameError,name 'farmers_market' is not defined,0,,2023-07-25 23:02:42.486935
3,SyntaxError,"invalid syntax (581900451.py, line 1)",0,,2023-07-26 14:32:44.668221
4,SyntaxError,"'(' was never closed (456139175.py, line 1)",0,,2023-07-26 14:34:57.149844
5,RuntimeError,"b'Traceback (most recent call last):\r\n  File ""<frozen runpy>"", line 198, in _run_module_as_main\r\n  File ""<frozen runpy>"", line 88, in _run_code\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\otter\\check\\validate_export\\__main__.py"", line 45, in <module>\r\n    main()\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\otter\\check\\validate_export\\__main__.py"", line 31, in main\r\n    results = grade_notebook(\r\n              ^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\otter\\execute\\__init__.py"", line 85, in grade_notebook\r\n    gp = GradingPreprocessor(config=c)\r\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\nbconvert\\preprocessors\\base.py"", line 42, in __init__\r\n    super().__init__(**kw)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\configurable.py"", line 109, in __init__\r\n    self.config = config\r\n    ^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 732, in __set__\r\n    self.set(obj, value)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 721, in set\r\n    obj._notify_trait(self.name, old_value, new_value)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 1505, in _notify_trait\r\n    self.notify_change(\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 1517, in notify_change\r\n    return self._notify_observers(change)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 1564, in _notify_observers\r\n    c(event)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 1146, in compatible_observer\r\n    return func(self, change)\r\n           ^^^^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\configurable.py"", line 218, in _config_changed\r\n    self._load_config(change.new, traits=traits, section_names=section_names)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\configurable.py"", line 181, in _load_config\r\n    setattr(self, name, deepcopy(config_value))\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 732, in __set__\r\n    self.set(obj, value)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 706, in set\r\n    new_value = self._validate(obj, value)\r\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 738, in _validate\r\n    value = self.validate(obj, value)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 2536, in validate\r\n    self.error(obj, value)\r\n  File ""C:\\Users\\NP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\traitlets.py"", line 844, in error\r\n    raise TraitError(e)\r\ntraitlets.traitlets.TraitError: The \'test_dir\' trait of a GradingPreprocessor instance expected a unicode string, not the NoneType None.\r\n'",0,,2023-07-26 14:44:26.671029
