0,SyntaxError,"can't assign to literal (2912417615.py, line 1)",0,,2023-07-24 20:06:02.198159,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 101)]","['Traceback (most recent call last):', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3226, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\IPython\\core\\compilerop.py"", line 101, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""C:\\Users\\NP\\AppData\\Local\\Temp\\ipykernel_27836\\2912417615.py"", line 1', ""SyntaxError: can't assign to literal""]"
1,RuntimeError,"b'Traceback (most recent call last):\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\runpy.py"", line 193, in _run_module_as_main\r\n    ""__main__"", mod_spec)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\runpy.py"", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\validate_export\\__main__.py"", line 45, in <module>\r\n    main()\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\validate_export\\__main__.py"", line 34, in main\r\n    cwd=os.getcwd()\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\execute\\__init__.py"", line 85, in grade_notebook\r\n    gp = GradingPreprocessor(config=c)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\nbconvert\\preprocessors\\base.py"", line 42, in __init__\r\n    super().__init__(**kw)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\config\\configurable.py"", line 109, in __init__\r\n    self.config = config\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 732, in __set__\r\n    self.set(obj, value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 721, in set\r\n    obj._notify_trait(self.name, old_value, new_value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 1511, in _notify_trait\r\n    type=""change"",\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 1517, in notify_change\r\n    return self._notify_observers(change)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 1564, in _notify_observers\r\n    c(event)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 1146, in compatible_observer\r\n    return func(self, change)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\config\\configurable.py"", line 218, in _config_changed\r\n    self._load_config(change.new, traits=traits, section_names=section_names)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\config\\configurable.py"", line 181, in _load_config\r\n    setattr(self, name, deepcopy(config_value))\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 732, in __set__\r\n    self.set(obj, value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 706, in set\r\n    new_value = self._validate(obj, value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 738, in _validate\r\n    value = self.validate(obj, value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 2536, in validate\r\n    self.error(obj, value)\r\n  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\traitlets\\traitlets.py"", line 844, in error\r\n    raise TraitError(e)\r\ntraitlets.traitlets.TraitError: The \'test_dir\' trait of a GradingPreprocessor instance expected a unicode string, not the NoneType None.\r\n'",0,,2023-07-24 21:52:54.302907,"[('grader.export(pdf=False, run_tests=True)', 2), ('return wrapped(*args, **kwargs)', 157)]","['Traceback (most recent call last):', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\IPython\\core\\interactiveshell.py"", line 3553, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""C:\\Users\\NP\\AppData\\Local\\Temp\\ipykernel_27836\\2062233748.py"", line 2, in <module>', '    grader.export(pdf=False, run_tests=True)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\utils.py"", line 157, in grading_mode_disabled', '    return wrapped(*args, **kwargs)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\utils.py"", line 144, in incompatible', '    return wrapped(*args, **kwargs)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\utils.py"", line 194, in event_logger', '    raise e', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\utils.py"", line 188, in event_logger', '    results = wrapped(*args, **kwargs)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\notebook.py"", line 403, in export', '    results = grade_zip_file(zip_path, nb_path, self._path)', '  File ""c:\\users\\np\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\otter\\check\\utils.py"", line 82, in grade_zip_file', '    raise RuntimeError(results.stderr)', 'RuntimeError: b\'Traceback (most recent call last):\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\runpy.py"", line 193, in _run_module_as_main\\r\\n    ""__main__"", mod_spec)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\runpy.py"", line 85, in _run_code\\r\\n    exec(code, run_globals)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\otter\\\\check\\\\validate_export\\\\__main__.py"", line 45, in <module>\\r\\n    main()\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\otter\\\\check\\\\validate_export\\\\__main__.py"", line 34, in main\\r\\n    cwd=os.getcwd()\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\otter\\\\execute\\\\__init__.py"", line 85, in grade_notebook\\r\\n    gp = GradingPreprocessor(config=c)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\nbconvert\\\\preprocessors\\\\base.py"", line 42, in __init__\\r\\n    super().__init__(**kw)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\config\\\\configurable.py"", line 109, in __init__\\r\\n    self.config = config\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 732, in __set__\\r\\n    self.set(obj, value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 721, in set\\r\\n    obj._notify_trait(self.name, old_value, new_value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 1511, in _notify_trait\\r\\n    type=""change"",\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 1517, in notify_change\\r\\n    return self._notify_observers(change)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 1564, in _notify_observers\\r\\n    c(event)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 1146, in compatible_observer\\r\\n    return func(self, change)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\config\\\\configurable.py"", line 218, in _config_changed\\r\\n    self._load_config(change.new, traits=traits, section_names=section_names)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\config\\\\configurable.py"", line 181, in _load_config\\r\\n    setattr(self, name, deepcopy(config_value))\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 732, in __set__\\r\\n    self.set(obj, value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 706, in set\\r\\n    new_value = self._validate(obj, value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 738, in _validate\\r\\n    value = self.validate(obj, value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 2536, in validate\\r\\n    self.error(obj, value)\\r\\n  File ""c:\\\\users\\\\np\\\\appdata\\\\local\\\\programs\\\\python\\\\python37\\\\lib\\\\site-packages\\\\traitlets\\\\traitlets.py"", line 844, in error\\r\\n    raise TraitError(e)\\r\\ntraitlets.traitlets.TraitError: The \\\'test_dir\\\' trait of a GradingPreprocessor instance expected a unicode string, not the NoneType None.\\r\\n\'']"
